import os
import sys
import re
from typing import List, Dict, Any, Optional

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

try:
    from backend.models import GeneratedLocator
except ImportError:
    from models import GeneratedLocator


def generate_locators_for_element(el: Dict[str, Any]) -> List[GeneratedLocator]:
    locators: List[GeneratedLocator] = []

    test_id = el.get('testId') or el.get('data-testid')
    if test_id:
        locators.append(GeneratedLocator(
            strategy='testid',
            selector=f'[data-testid="{test_id}"]',
            confidence=0.99
        ))

    role = el.get('role')
    acc_name = (el.get('accessibleName') or el.get('text') or '').strip()
    if role and acc_name and len(acc_name) < 50:
        locators.append(GeneratedLocator(
            strategy='role',
            selector=f'role={role}[name="{acc_name}"]',
            confidence=0.95
        ))

    placeholder = el.get('placeholder')
    if placeholder:
        locators.append(GeneratedLocator(
            strategy='placeholder',
            selector=f'[placeholder="{placeholder}"]',
            confidence=0.90
        ))

    aria_label = el.get('ariaLabel') or el.get('aria-label')
    if aria_label:
        locators.append(GeneratedLocator(
            strategy='label',
            selector=f'[aria-label="{aria_label}"]',
            confidence=0.88
        ))

    text = el.get('text', '').strip()
    tag_name = el.get('tagName', '').upper()
    if text and tag_name in ('BUTTON', 'A', 'SPAN', 'P') and len(text) < 40:
        locators.append(GeneratedLocator(
            strategy='text',
            selector=f'text="{text}"',
            confidence=0.82
        ))

    # IMPORTANT: only use the element's real DOM "id" attribute (idAttr) here.
    # el['id'] is this tool's own internal bookkeeping key (e.g. "btn-4", "inp-2"),
    # not a real attribute on the page. Falling back to it produces a CSS selector
    # like "#btn-4" that matches nothing on the actual site and makes every click/fill
    # on an unlabeled element (icon buttons, unnamed inputs, etc.) fail.
    id_attr = el.get('idAttr')
    if id_attr and not re.match(r'^(react-|radix-|__next|ember|vue-|ng-)', id_attr, re.I):
        locators.append(GeneratedLocator(
            strategy='css',
            selector=f'#{id_attr}',
            confidence=0.80
        ))

    name = el.get('name')
    if name:
        locators.append(GeneratedLocator(
            strategy='css',
            selector=f'[name="{name}"]',
            confidence=0.75
        ))

    locators.append(GeneratedLocator(
        strategy='css',
        selector=tag_name.lower() or 'div',
        confidence=0.40
    ))

    return locators


def resolve_playwright_locator(page: Any, selector: str, strategy: Optional[str] = None) -> Any:
    """Resolves a selector string to a Playwright Python locator."""
    if strategy == 'role' and selector.startswith('role='):
        m = re.match(r'^role=([a-z0-9_-]+)\[name="(.+)"\]$', selector, re.I)
        if m:
            role, name = m.group(1), m.group(2)
            return page.get_by_role(role, name=name.strip())

    # NOTE: these selector strings are sometimes a single strategy-specific pattern
    # (e.g. `[placeholder="Full Name"]`) and sometimes a comma-separated *list* of
    # fallback CSS selectors (e.g. `[name="x"], [placeholder="y"], input[type="text"]`)
    # generated by the test generator. The character class `[^"]+` (instead of a
    # greedy `.+`) makes sure we only ever capture the text between the *nearest*
    # pair of quotes, so a match inside a longer comma-separated list can't "leak"
    # into the next clause and produce a garbage/nonexistent target string.
    if strategy == 'placeholder' or selector.startswith('[placeholder='):
        m = re.search(r'\[placeholder="([^"]+)"\]', selector)
        if m:
            return page.get_by_placeholder(m.group(1))

    if strategy == 'label' or selector.startswith('[aria-label='):
        m = re.search(r'\[aria-label="([^"]+)"\]', selector)
        if m:
            return page.get_by_label(m.group(1))

    if strategy == 'testid' or selector.startswith('[data-testid='):
        m = re.search(r'\[data-testid="([^"]+)"\]', selector)
        if m:
            return page.get_by_test_id(m.group(1))

    if strategy == 'text' or selector.startswith('text='):
        m = re.search(r'^text="(.+)"$', selector)
        if m:
            return page.get_by_text(m.group(1))

    # Raw/combined CSS selector (possibly a comma-separated list of fallback
    # candidates). Use `.first` because these lists are intentionally "match any
    # of these" candidates rather than a single specific element — without this,
    # Playwright's strict mode throws when more than one candidate matches
    # (e.g. two <input> fields both matching "input:not([type=hidden])"),
    # which previously failed tests even though the page behaved correctly.
    return page.locator(selector).first


async def attempt_self_healing(page: Any, failed_selector: str, target_description: str) -> Optional[Dict[str, Any]]:
    """Self-healing locator fallback engine for Playwright Python."""
    clean_desc = re.sub(r'^(click|fill|select|check|submit)\s+', '', target_description, flags=re.I)
    clean_desc = clean_desc.replace('"', '').replace("'", "").strip()

    if len(clean_desc) > 1:
        # Strategy 1: Visible Text Search
        try:
            text_loc = page.get_by_text(clean_desc, exact=False).first
            if await text_loc.is_visible(timeout=1500):
                return {
                    'recovered_locator': text_loc,
                    'recovered_selector': f'text="{clean_desc}"',
                    'strategy': 'text',
                    'confidence': 0.85,
                    'reason': f'Found matching element by visible text content "{clean_desc}"'
                }
        except Exception:
            pass

        # Strategy 2: Button / Link Role Search
        try:
            btn_loc = page.get_by_role('button', name=clean_desc).first
            if await btn_loc.is_visible(timeout=1500):
                return {
                    'recovered_locator': btn_loc,
                    'recovered_selector': f'role=button[name="{clean_desc}"]',
                    'strategy': 'role',
                    'confidence': 0.90,
                    'reason': f'Found accessible button role with name "{clean_desc}"'
                }
        except Exception:
            pass

        # Strategy 3: Placeholder Search (useful for recovering broken "fill" targets,
        # e.g. "Fill fullname" -> looks for an input with placeholder/label "fullname")
        try:
            ph_loc = page.get_by_placeholder(clean_desc, exact=False).first
            if await ph_loc.is_visible(timeout=1500):
                return {
                    'recovered_locator': ph_loc,
                    'recovered_selector': f'[placeholder*="{clean_desc}"]',
                    'strategy': 'placeholder',
                    'confidence': 0.85,
                    'reason': f'Found input field by placeholder text matching "{clean_desc}"'
                }
        except Exception:
            pass

        # Strategy 4: Accessible Label Search (form fields with an associated <label>)
        try:
            label_loc = page.get_by_label(clean_desc, exact=False).first
            if await label_loc.is_visible(timeout=1500):
                return {
                    'recovered_locator': label_loc,
                    'recovered_selector': f'[aria-label*="{clean_desc}"]',
                    'strategy': 'label',
                    'confidence': 0.85,
                    'reason': f'Found input field by accessible label matching "{clean_desc}"'
                }
        except Exception:
            pass

    return None
